apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: disk.csi.zenlayer.com
spec:
  attachRequired: true
  podInfoOnMount: false
  volumeLifecycleModes: 
    - Persistent
  requiresRepublish: false 
