name: Refresh Go Report Card

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Refresh Go Report Card
        uses: creekorful/goreportcard-action@v1.0
